### ISSUE TITLE
undocumented shaper settings

### ISSUE THREAD

**Issue by mightyBroccoli** [processone/docs.ejabberd.im#93]
After reading the newest blog post I noticed that the shaper options used in it aren't documented.
```yml
shaper:
  normal:
    rate: 3000
    burst_size: 20000
```
